### ISSUE TITLE
NMS changes in 1.17

### ISSUE THREAD

**Issue by rchomczyk** [OkaeriPoland/okaeri-commons#1]
## Description
**okaeri-platform** is breaking while using [UnsafeBukkitCommons](https://github.com/OkaeriPoland/okaeri-commons/blob/master/bukkit/src/main/java/eu/okaeri/commons/bukkit/UnsafeBukkitCommons.java), because of changes in NMS.

## Stacktrace
https://paste.gg/p/anonymous/92fee23f9f434ba687fe7782708097e5

## Changelog
Changelog is available [there](https://www.spigotmc.org/threads/spigot-bungeecord-1-17-1-17-1.510208/).

**Comment by sandrwich** [comment]
Fixed in https://github.com/OkaeriPoland/okaeri-commons/commit/89225b09375b9a85f3c9b72c1827f22206c13a75
